#!/bin/bash

# Example of how to generate a generator class

./openapi-generator-cli meta -n DocSpringClient -o generators/ruby \
  -t CLIENT \
  -p com.docspring.codegen


# Compile it
mvn package -DskipTests=true


# Use it:
java -cp generators/ruby/target/DocSpringClient-openapi-generator-1.0.0.jar\
:openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar \
org.openapitools.codegen.OpenAPIGenerator help
