#!/bin/bash
set -e
cd "$(dirname "$0")/../"

LANGUAGE="$1"

if [ -z "$LANGUAGE" ]; then
  for f in config/*; do
    LANG="$(echo $f | sed -e "s/config\///g" -e "s/\.json//g")"
    echo "Running integration tests for $LANG client library..."
    ./scripts/run_integration_tests "$LANG"
  done
  exit
fi

SPEC_FILE="spec/api_clients/${LANGUAGE}_client_spec.rb"
cd ..

if [ -f ~/.rvm/scripts/rvm ]; then
  # Need to use correct Ruby version on Mac.
  source ~/.rvm/scripts/rvm
  rvm use
fi

echo "[api_clients] Running API client test script for $LANGUAGE... (${SPEC_FILE})"

# If we're in a docker container, don't use Spring.
if [ -f /etc/docker_base_image_id ]; then
  RSPEC_CMD="rspec"
else
  RSPEC_CMD="./bin/rspec"
fi

RUN_API_CLIENT_TESTS=true TEST_ARGS="${@:2}" "$RSPEC_CMD" "${SPEC_FILE}"
